# Name of the composite action
name: maple
  
runs:
  using: "composite"
  steps:
    - run: mkdir -p $HOME/.local/bin && export PATH="PATH:$HOME/.local/bin"
      shell: bash
    - run: cd ~/Maple && ./setup develop && ./setup install
      shell: bash
    - run: rm -rf ~/Maple
      shell: bash
