# Name of the composite action
name: install

inputs:
  workdir: 
    description: 'Working directory for maple'
    default: ${{env.working_directory}}
  
runs:
  using: "composite"
  steps:
    - run: mkdir -p $HOME/.local/bin && export PATH="PATH:$HOME/.local/bin"
      shell: bash
    - run: cd ${{inputs.workdir}} ./setup develop && ./setup install
      shell: bash
