# Name of the composite action
name: maple
  
runs:
  using: "composite"
  steps: 
    - run: git clone https://github.com/akashdhruv/Maple.git 
      shell: bash
    - run: mkdir -p $HOME/.local/bin && export PATH="PATH:$HOME/.local/bin"
      shell: bash
    - run: cd Maple && PWD
      shell: bash
    - run: PWD
      shell: bash
    - run: ./setup develop && ./setup clean
      shell: bash
