#!/bin/bash

source $2

if [ $1 = "build" ]; then
docker build -t $maple_container --build-arg maple_image=$maple_image \
                                 --build-arg maple_parfile=$maple_parfile .

fi

if [ $1 = "rebuild" ]; then
docker-compose build -t $maple_container --build-arg maple_image=$maple_image \
                                         --build-arg maple_parfile=$maple_parfile .

fi

if [ $1 = "run" ]; then
docker run -v $PWD/IOData/IOData_$maple_container:/home/run/IOData $maple_container
fi

if [ $1 = "pour" ]; then
docker pull $maple_image
docker run -dit --name $maple_container $maple_image bash
fi

if [ $1 = "bash" ]; then
docker exec -it $maple_container bash
fi

if [ $1 = "stop" ]; then
docker stop $maple_container
docker rm $maple_container
fi

if [ $1 = "clean" ]; then
docker rmi -f $maple_container
fi
