#!/bin/bash

docker build -t $1_container:$2 --build-arg maple_image=akashdhruv/$1:$2 \
                                --build-arg maple_parfile=./parfiles/parfile.$1:$2 \
                                --build-arg solver_parfile=flash.par .

docker run --env solver_exe=flash4 -v $PWD/IOData/IOData_$1_$2:/home/run/IOData $1_container:$2
