#!/usr/bin/env python3

import click

@click.group()
def maple():
    """
    Simple CLI for querying books on Google Books by Oyetoke Toby
    """
    pass

@maple.command()
@click.argument('maple_image')
def pull(maple_image):
    pass

@maple.command()
@click.argument('maple_container')
def push(maple_container):
    pass

if __name__ == "__main__":
    maple()
