#!/bin/bash

# Development mode (required before install)
if [ $1 = "develop" ]; then
    python3 setup.py develop --user
    cp maple/maple $HOME/.local/bin
    mkdir -p $HOME/.local/maple
fi

# Install mode 
if [ $1 = "install" ]; then
    python3 setup.py build
    python3 setup.py install --user
    cp maple/maple $HOME/.local/bin
    mkdir -p $HOME/.local/maple
fi

# Clean after installation
if [ $1 = "clean" ]; then
   rm -rf *.egg-info
   rm -rf build dist
fi
