#!/usr/bin/env python3

""" MAPLE is wrapper around containerization tools like docker/singularity 
    to provide support for HPC applications.
"""

import maple

if __name__ == "__main__":
    maple.cli.maple()
