# Name of the composite action
name: install
 
runs:
  using: "composite"
  steps:
    - run: pip3 install click
      shell: bash
    - run: mkdir -p $HOME/.local/bin && export PATH="PATH:$HOME/.local/bin"
      shell: bash
    - run: ./setup install && ./setup clean
      shell: bash
