# Name of the composite action
name: install
  
runs:
  using: "composite"
  steps:
    - run: mkdir -p $HOME/.local/bin && export PATH="PATH:$HOME/.local/bin"
      shell: bash
    - run: ./setup develop && ./setup install
      shell: bash
