# Build image using user privileges
ARG maple_uid
ARG maple_gid
ARG maple_user

ENV maple_gid=${maple_gid}
ENV maple_uid=${maple_uid}
ENV maple_user=${maple_user}

RUN bash -c 'if [[ ${OSTYPE} == linux-gnu ]] ; then addgroup --gid ${maple_gid} ${maple_user} ; fi'
RUN bash -c 'adduser --disabled-password --gecos ',,,,' --uid ${maple_uid} --gid ${maple_gid} ${maple_user}'

USER ${maple_user}

# MPI environment variable
ENV OMPI_MCA_btl_vader_single_copy_mechanism=none

