# Dockerfile for maple

# Build from a base image
ARG maple_base
FROM ${maple_base}

# Add current user to container (comment when trying to login as root)
USER root

# Set working directory using maple_target from Maplefile
ARG maple_target
WORKDIR $maple_target
