# Build local image from base image
ARG maple_base
FROM ${maple_base}

ARG maple_workdir
WORKDIR ${maple_workdir}

ARG maple_mpi
ENV MPI_ROOT=${maple_mpi}
ENV PATH=$MPI_ROOT/bin:$PATH
ENV LD_LIBRARY_PATH=$MPI_ROOT/lib:$LD_LIBRARY_PATH
ENV INCLUDE=$MPI_ROOT/include:$INCLUDE
ENV C_INCLUDE_PATH=$MPI_ROOT/include:$C_INCLUDE_PATH
ENV CPLUS_INCLUDE_PATH=$MPI_ROOT/include:$CPLUS_INCLUDE_PATH
