# Base Docker file for maple
# 

# Build local image from base image
ARG maple_base
FROM ${maple_base}

# Build image using root privileges
USER root

# MPI environment variable
ENV OMPI_MCA_btl_vader_single_copy_mechanism=none

