# GitHub workflos for examples/bubblebox
name: BubbleBox

# Launch workflow during pull request to main
# branch
on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'
      - 'docs/'

# Define jobs here
jobs:

  # job to test Command Line Interface (CLI)
  cli:
    name: "CLI"
    runs-on: ubuntu-latest
    steps:
    
    # Login to Docker Hub account
    # 
    - name: Login to Docker Hub
      run: |
          echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    - uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PSK}}

    # Checkout repositories and install Maple
    #
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install

    # Run example
    - name: Run examples/bubblebox
      run: |
          cd examples/bubblebox
          maple image build bubblebox ${{secrets.DOCKER_HUB_USERNAME}}/bubblebox:latest
          maple container pour --image=bubblebox
          maple container execute "python3 example.py"
          maple container rinse
          maple image delete bubblebox
