# GitHub workflos for examples/bubblebox
name: BubbleBox

# Launch workflow during pull request to main
# branch
on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'
      - 'docs/'

# Define jobs here
jobs:

  # job to test Command Line Interface (CLI)
  CLI:
    name: "CLI"
    runs-on: ubuntu-latest
    steps:
    #- name: Login to Docker Hub
    #  run: |
    #      echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    #- uses: docker/login-action@v1
    #  with:
    #    username: ${{secrets.DOCKER_HUB_USERNAME}}
    #    password: ${{secrets.DOCKER_HUB_PSK}}
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install
    - name: Run examples/bubblebox
      run: |
          cd examples/bubblebox
          maple image build bubblebox -B ${{secrets.DOCKER_HUB_USERNAME}}/bubblebox:latest
          maple container pour -I bubblebox
          maple container execute "python3 example.py"
          maple container rinse
          maple image delete bubblebox
