name: bubblebox

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'
      - 'docs/'

jobs:
  example:
    name: "example"
    - uses: ./.github/workflows/maple-env.yml
    - name: Run examples/bubblebox
      run: |
          cd examples/bubblebox
          maple image build
          maple container execute "python3 example.py"
          maple image clean
          maple image remove
