name: create

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'
      - 'docs/'

jobs:
  cli:
    name: "cli"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eWaterCycle/setup-singularity@v7
    - uses: ./.github/actions/install
    - name: Run examples/create
      run: |
          cd examples/create
          maple image build local
          maple container pour --image=local
          maple container execute
          maple container rinse
          maple image delete local
          
  api:
    name: "api"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install
    - name: Run examples/create
      run: |
          cd examples/create
          python3 MapleAPI.py
