name: create-container

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:
  ubuntu-latest:
    name: "ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: Dependencies1
      run: |
          mkdir -p $HOME/.local/bin
          export PATH="PATH:$HOME/.local/bin"
    - name: Setup PyMaple
      run: |
          ./setup develop
          ./setup clean
    - name: Run examples/create
      run: |
          cd examples/create
          maple build
          maple run
          maple pour
          maple execute
          maple rinse
          maple clean
          maple remove
          python3 MapleAPI.py
