name: create

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'
      - 'docs/'

jobs:
  example:
    name: "example"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eWaterCycle/setup-singularity@v7
    - uses: ./.github/actions/maple
    - name: Run examples/create
      run: |
          cd examples/create
          maple image build
          maple container execute
          maple image clean
          maple image remove
          python3 MapleAPI.py
