name: flashx

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'
      - 'docs/'

jobs:         
  boiling-cli:
    name: "boiling-cli"
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      run: |
          echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    - uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME }}
        password: ${{secrets.DOCKER_HUB_PSK}}   
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install
    - name: Run examples/flashx
      run: |
          cd examples/flashx/boiling
          maple image build boiling ${{secrets.DOCKER_HUB_USERNAME}}/flash:boiling
          maple container pour --image=boiling
          maple container execute "mpirun -n 1 /home/run/flash4"
          maple container rinse
          maple image delete boiling

  boiling-api:
    name: "boiling-api"
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      run: |
          echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    - uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PSK}}   
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install
    - uses: eWaterCycle/setup-singularity@v7
    - name: Run examples/flashx
      run: |
          cd examples/flashx/boiling
          python3 MapleAPI.py

  lidcav-cli:
    name: "lidcav-cli"
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      run: |
          echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    - uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PSK}}   
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install
    - uses: eWaterCycle/setup-singularity@v7
    - name: Run examples/flashx
      run: |
          apt-get install -y libopenmpi-dev openmpi-bin
          cd examples/flashx/lidcav
          maple image build lidcav
          mpirun -n 1 maple container run --image=lidcav "/home/run/flashx"
