name: flashx

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'
      - 'docs/'

jobs:         
  cli:
    name: "cli"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install
    - name: Run examples/flashx
      run: |
          cd examples/flashx
          maple image build local
          maple container pour --image=local
          maple container execute "mpirun -n 1 /home/run/flash4"
          maple container rinse
          maple image delete local

  api:
    name: "api"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install
    - uses: eWaterCycle/setup-singularity@v7
    - name: Run examples/flashx
      run: |
          cd examples/flashx
          python3 MapleAPI.py
