name: flash-container

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'
      - 'docs/'

jobs:
  ubuntu-latest:
    name: "ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: Dependencies1
      run: |
          mkdir -p $HOME/.local/bin
          export PATH="PATH:$HOME/.local/bin"
    - name: Setup Maple
      run: | 
          ./setup develop
          ./setup clean
    - name: Run examples/flashsim
      run: |
          cd examples/flashsim
          maple image build
          maple container execute "export OMPI_MCA_btl_vader_single_copy_mechanism=none && \
                                   mpirun -n 1 /home/run/flash4"
          maple image clean
          maple image remove
          python3 MapleAPI.py
