name: flash

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'
      - 'docs/'

jobs:
  example:
    name: "example"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/maple@v1
    - name: Run examples/flashsim
      run: |
          cd examples/flashsim
          maple image build
          maple container execute "export OMPI_MCA_btl_vader_single_copy_mechanism=none && \
                                   mpirun -n 1 /home/run/flash4"
          maple image clean
          maple image remove
          python3 MapleAPI.py
