# GitHub workflow for flashx application
name: FlashX

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'
      - 'docs/'

# Worflow jobs listed below
jobs:         

  CLI:
    name: "CLI"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install
    - name: Run examples/flashx
      run: |
          cd examples/flashx/boiling
          maple image build boiling
          maple container pour -I boiling
          maple container execute "mpirun -n 1 /home/run/flashx"
          maple container rinse
          maple image delete boiling

  API:
    name: "API"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install
    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3
    - name: Run examples/flashx
      run: |
          cd examples/flashx/boiling
          python3 MapleAPI.py

  MPI:
    name: "MPI"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install
    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3 
    - name: Run examples/flashx
      run: |
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt-get install -y libopenmpi-dev openmpi-bin
          cd examples/flashx/lidcav
          maple image build lidcav
          mpirun -n 1 maple container run -I lidcav
