name: flash

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'
      - 'docs/'

jobs:
  cli:
    name: "cli"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install
    - name: Run examples/flashsim
      run: |
          cd examples/flashsim
          maple image build
          maple container execute "mpirun -n 1 /home/run/flash4"
          maple container clean
          maple image remove

  api:
    name: "api"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install
    - name: Run examples/flashsim
      run: |
          cd examples/flashsim
          python3 MapleAPI.py
