# GitHub workflows for examples/flowx
name: FlowX

# Launch workflow during pull request to main
# branch
on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'
      - 'docs/'

# Define jobs here
jobs:

  API:
    name: "API"
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      run: |
          echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    #- uses: docker/login-action@v1
    #  with:
    #    username: ${{secrets.DOCKER_HUB_USERNAME}}
    #    password: ${{secrets.DOCKER_HUB_PSK}}
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install
    - name: Run examples/flowx
      run: |
          cd examples/flowx
          python3 MapleAPI.py
