name: Minimal

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'
      - 'docs/'

jobs:

  cli:
    name: "CLI"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eWaterCycle/setup-singularity@v7
    - uses: ./.github/actions/install
    - name: Run examples/minimal
      run: |
          cd examples/minimal
          maple image build minimal docker://ubuntu:latest
          maple container pour --image=minimal
          maple container execute
          maple container rinse
          maple image delete minimal
          
  api:
    name: "API"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install
    - name: Run examples/minimal
      run: |
          cd examples/minimal
          python3 MapleAPI.py
