name: tests-api

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'
      - 'docs/'

jobs:
  create:
    name: "create"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install
    - name: Run examples/create
      run: |
          cd examples/create
          python3 MapleAPI.py

  flash:
    name: "flash"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install
    - name: Run examples/flashsim
      run: |
          cd examples/flashsim
          python3 MapleAPI.py
